"""Add Books table

Revision ID: 935abbf98b48
Revises: a0c8a73afa4e
Create Date: 2024-04-22 15:44:33.078869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935abbf98b48'
down_revision = 'a0c8a73afa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=False),
    sa.Column('publisher', sa.String(length=150), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('print_length', sa.String(length=150), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('isbn', sa.String(length=200), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('publisher', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('print_length', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('owner_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_token'], ['user.token'], name='book_owner_token_fkey'),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    op.drop_table('books')
    # ### end Alembic commands ###
